version: "3.8"
services:
  app:
    container_name: blog-wip
    image: ruby:latest
    command: bash -c ". /app/scripts/start.sh"
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "4000:4000"
      - "4001:4001"
